export const ErrorCode = {
    BAD_REQUEST: 400,
    ADMIN_UNAUTHORIZED: 403,
  
    CATEGORY_NOT_FOUND: 1000,
    CATEGORY_ALREADY_EXIST: 1001,
  
    PROGRAM_NOT_FOUND: 2000,
  
    STAMP_CARD_NOT_FOUND: 3000,
    STAMP_CARD_ALREADY_EXIST: 3001,
  
    ALREADY_PARTICIPATED: 4000,
    DISTANCE_OUT_OF_RANGE: 4001,
    PROGRAM_NOT_WITHIN_PARTICIPATION_TIME: 4002,
    INVALID_DATE_TIME_FORMAT: 4003,
  
    STUDENT_ID_ALREADY_EXISTS: 5000,
    USER_NOT_FOUND: 5001,
    PASSWORD_MISMATCH: 5002,
    EMAIL_ALREADY_EXISTS: 5003,
    TOKEN_NOT_FOUND: 5004,
    TOKEN_NOT_EXPIRED: 5005,
    TOKEN_EXPIRED: 5006,
    EMAIL_NOT_VERIFIED: 5007,
    DEVICE_NOT_FOUND: 5008,
    DEVICE_NOT_MATCH: 5009,
  
    PRIZE_NOT_FOUND: 6000,
    PRIZE_WINNER_NOT_FOUND: 6001,
    PRIZE_WINNER_ALREADY_CLAIMED: 6002,
    NOT_ENOUGH_ELIGIBLE_PARTICIPANTS: 6003,
  
    INTERNAL_SERVER_ERROR: 9999,
  } as const;

export type ErrorCodeType = typeof ErrorCode;
export type ErrorCodeValue = ErrorCodeType[keyof ErrorCodeType];
export type ErrorCodeKey = keyof ErrorCodeType;